### PR TITLE
Print yarn version

### PR DESCRIPTION
**Pull request by trapacska**
Hey, it's Tamas from Bitrise!

Printing yarn version will decrease the overhead of finding info when a bug report happens or so.
It would be very nice of you if you could accept this PR and release a new version of the step.

Please let us know if you need further help or if you have a question / concern about this PR.

Thank you very much!
🚀

### CODE REVIEW

**Comment by jonoirwinrsa** [comment]
Hey @trapacska 

Thanks for the PR. I have merged and created a release - https://github.com/bitrise-io/bitrise-steplib/pull/1464

**Comment by viktorbenei** [comment]
Awesome, thanks both! ;)

**Comment by jonoirwinrsa** [comment]
@trapacska and @viktorbenei I have a question/concern that is not directly linked to this PR but I suspect you might be able to help me out with. Its in relation to the issue raised here: https://github.com/jonoirwinrsa/steps-yarn/issues/3

Should my step.sh run `yarn ${command} ${options} ${args}` in order to run the options entered by a user on Bitrise? - the difference being the addition of the "`${args}`"

**Comment by viktorbenei** [comment]
Should be `yarn ${x} ${y}` where `x` and `y` are the inputs of your step.

Checking the step.yml (https://github.com/jonoirwinrsa/steps-yarn/blob/master/step.yml) it seems you have `command` and `args` inputs, but no `options`, so in your step.sh you should reference `${command}` and `${args}`, not `${options}` as you don't have an `options` input.

In short, you can access inputs in bash this way: `${input_id}` - but only those which you registered in the step.yml as input, and with the "input id" you register there!

Let me know if you'd have any questions! ;)

**Pull request merged**
